name: samp_query
description: A package that implements the SA:MP query mechanism for getting data about a running server. Written in pure Dart.
version: 0.1.0
homepage: https://github.com/artplaygamesofc/samp_query

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.2.4

dev_dependencies:
  pedantic: ^1.10.0
