name: Dart CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: pub get
# Disable tests for now as GitHub does not allow calls out.
# Really we should have local XML/JSON files for testing.
#    - name: Run tests
#      run: pub run test
